### ISSUE TITLE
Add HoneyCon

### ISSUE THREAD

**Issue by seadog007** [s3131212/gotyour.pw#14]
One new resource
name: HoneyCon
url: http://2015.honeynet.org.tw/
descriptions: 台灣誘捕網路技術研討會，是台灣稀少的資安年會之一

@s3131212 這樣可以嗎?

**Comment by s3131212** [comment]
不至於到稀少吧 XDDDDD

**Comment by seadog007** [comment]
那大大要怎麼改呢XD

**Comment by s3131212** [comment]
台灣誘捕網路技術研討會，是台灣的資安年會之一
