### ISSUE TITLE
台灣區 Botnet 偵測與防治技術研討會

### ISSUE THREAD

**Issue by denny0223** [s3131212/gotyour.pw#16]
http://anti-botnet.edu.tw/content/confs/BoT2014.html

**Comment by seadog007** [comment]
只有2014 考慮Close

**Comment by seadog007** [comment]
等今年網站出來

**Comment by denny0223** [comment]
12 至今的 html 都有 自己改網址~

**Comment by denny0223** [comment]
http://www.anti-botnet.edu.tw/index.html
原來有計畫的網站

**Comment by pcchou** [comment]
新增 http://www.anti-botnet.edu.tw/index.html 好了，
我現在去弄
