### ISSUE TITLE
網站強致走HTTPS可能會造成的問題

### ISSUE THREAD

**Issue by seadog007** [s3131212/gotyour.pw#17]
Mixed Content: The page at 'https://gotyour.pw/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,300italic,400italic'. This request has been blocked; the content must be served over HTTPS.

**Comment by denny0223** [comment]
那就換 https 啊

**Comment by seadog007** [comment]
對啊 所以給 sd+

**Comment by s3131212** [comment]
我想一定是我智商太高，只有我知道可以改成 https

**Comment by seadog007** [comment]
別自戀了 快改~~ Chrome連哪一行都寫出來了啊XDD
