### ISSUE TITLE
New resources

### ISSUE THREAD

**Issue by seadog007** [s3131212/gotyour.pw#18]
https://mega.co.nz/#!5ccB2KZC!IysjFdbjGqR9ovmGmJwMGlel4vfpj14PIJhDT-PfzJs
http://fumalwareanalysis.blogspot.tw/p/malware-analysis-tutorials-reverse.html
http://mirror7.meh.or.id/

**Comment by s3131212** [comment]
已加上
#c1830af

**Comment by seadog007** [comment]
看來 @s3131212 不會用Github
有人要教教他用Commit close issue嗎

**Comment by denny0223** [comment]
commit message Fix #1 就會關了
https://help.github.com/articles/closing-issues-via-commit-messages/

訊息提到特定 commit 的話 c1830af 就好
