### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by hang333** [s3131212/gotyour.pw#24]
![capture](https://cloud.githubusercontent.com/assets/3853064/7552714/f0585bcc-f6f7-11e4-936b-e1ff2834efba.JPG)

**Comment by pcchou** [comment]
唉呀，早上剛起來砍 issue，腦袋不好沒看到

沒想到這麼早就有人注意了！

**Comment by pcchou** [comment]
結果還沒修好 怒

**Comment by s3131212** [comment]
都不讓我重開 QAQ

**Comment by hang333** [comment]
为啥重开 o.o

**Comment by pcchou** [comment]
#25
