### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by hang333** [s3131212/gotyour.pw#25]
讨厌CDN，缓存更新好慢

**Comment by pcchou** [comment]
這應該不是CF的問題吧…

CF更新應該是接近無感，因為也沒調什麼真的有感的加速

**Comment by pcchou** [comment]
你可以清清看 browser cache?

**Comment by hang333** [comment]
没用的嘎～但是刚才CF的缓存已经更新了

**Comment by pcchou** [comment]
現在網域在 @seadog007 的帳號下，他可能還在熟睡中無法回應 request…

**Comment by pcchou** [comment]
還真的是 CF 的問題，
之後請 @seadog007 把 CF caching 關掉，反正 GitHub Pages 也打不死XD

**Comment by s3131212** [comment]
終於搞定這個蠢問題了（汗
