### ISSUE TITLE
Add an "about" page

### ISSUE THREAD

**Issue by pcchou** [s3131212/gotyour.pw#9]
as we discussed about it in ADJP yesterday

**Comment by seadog007** [comment]
XDDD 自己開的issue自己做

**Comment by seadog007** [comment]
做法參考 #10

**Comment by seadog007** [comment]
阿棍= = 整個亂掉了QAQQQ

**Comment by s3131212** [comment]
所以現在是在搞啥啊 ....
自己的 Issue 自己幹 (?

**Comment by seadog007** [comment]
這很重要誒OuO 乖 Reopen

**Comment by pcchou** [comment]
已開 about feature branch, 煩請大家填寫資料(?

目前是 Lorem Ipsum 這樣

**Comment by s3131212** [comment]
我們現在有好棒棒的 About Us 了 :)
d63fd9f
